### ISSUE TITLE
Downloaded latest release a few times

### ISSUE THREAD

**Issue by ashaikh** [runew0lf/RuinedFooocus#100]
When extracting on Windows 10 with all the latest updates, I get this error: Unsupported Compression Method. I am using x86-64 AMD system not arm. Is your upload corrupted?

![image](https://github.com/runew0lf/RuinedFooocus/assets/118411/7290ac4e-563e-4759-8907-2a3aca6f7865)

**Comment by crack2483** [comment]
I'm having the same issue. Intel i9/Nvidia system.

**Comment by crack2483** [comment]
> windows archiving doesn't work correcly with 7zip extraction correctly, just extract with 7zip and you're golden!

I'll give it a try again. but I am using 7zip

**Comment by crack2483** [comment]
I've tried all options with 7Zip and still getting the same errors

**Comment by runew0lf** [comment]
grab the latest version of 7zip mate

**Comment by runew0lf** [comment]
User used 7zip, closing ticket

**Comment by ashaikh** [comment]
Older version of 7zip did not work but the latest did. Thanks for the heads up.
