### ISSUE TITLE
After window opens, type something, click generate, just sits at "Please Wait"

### ISSUE THREAD

**Issue by jordanbr20** [runew0lf/RuinedFooocus#101]
as the title says, just sits at Please wait

C:\Windows\system32>C:\Users\USER\Desktop\RuinedFooocus\python_embeded\python.exe -s C:\Users\USER\Desktop\RuinedFooocus\RuinedFooocus\entry_with_update.py
Update failed...
failed to send request: The connection with the server was terminated abnormally

Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
RuinedFooocus version: 1.25.2
Comfy Backend exists.
Git clone failed for Comfy Backend: failed to send request: The connection with the server was terminated abnormally

Total VRAM 8192 MB, total RAM 32679 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 Quadro RTX 4000 : native
Using xformers cross attention
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\Users\USER\Desktop\RuinedFooocus\RuinedFooocus\modules\async_worker.py", line 34, in worker
    import modules.pipelines
  File "C:\Users\USER\Desktop\RuinedFooocus\RuinedFooocus\modules\pipelines.py", line 4, in <module>
    import modules.sdxl_pipeline as sdxl_pipeline
  File "C:\Users\USER\Desktop\RuinedFooocus\RuinedFooocus\modules\sdxl_pipeline.py", line 34, in <module>
    from comfy.sample import (
ImportError: cannot import name 'convert_cond' from 'comfy.sample' (C:\Users\USER\Desktop\RuinedFooocus\RuinedFooocus\repositories\ComfyUI-from-StabilityAI-Official\comfy\sample.py)
Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.

**Comment by runew0lf** [comment]
Git clone failed for Comfy Backend: failed to send request: The connection with the server was terminated abnormally
re-run mate, your comfy isnt updating

**Comment by jordanbr20** [comment]
> Git clone failed for Comfy Backend: failed to send request: The connection with the server was terminated abnormally re-run mate, your comfy isnt updating

I have re-run it multiple times. How do I do it manually?

**Comment by jordanbr20** [comment]
So heres what I did to fix it:

Opened RuinedFooocus\Repositories
Deleted "ComfyUI-from-StabilityAI-Official

Went to - https://github.com/comfyanonymous/ComfyUI
Downloaded as Zip
Extraced to the repositories folder
Renamed it "ComfyUI-from-StabilityAI-Official"

Restarted and now it works :)

Although, it still says it needs to update and updated failed -_-


C:\Windows\system32>C:\Users\USER\Desktop\RuinedFooocus\python_embeded\python.exe -s C:\Users\USER\Desktop\RuinedFooocus\RuinedFooocus\entry_with_update.py
Update failed...
failed to send request: The connection with the server was terminated abnormally

Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
RuinedFooocus version: 1.25.2
Comfy Backend exists.
Git clone failed for Comfy Backend: failed to send request: The connection with the server was terminated abnormally

Total VRAM 8192 MB, total RAM 32679 MB
xformers version: 0.0.20
Set vram state to: NORMAL_VRAM
Device: cuda:0 Quadro RTX 4000 : native
VAE dtype: torch.float32
Using xformers cross attention
Loading base model: sd_xl_base_1.0_0.9vae.safetensors
Base model loaded: sd_xl_base_1.0_0.9vae.safetensors
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
