### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by mesopa** [runew0lf/RuinedFooocus#102]
Two suggestions if you guys don't mind:
- Update the README and instead of running the command `conda activate fooocus` please update to `conda activate ruinedfooocus`
- If you stumble into `Torch not compiled with CUDA enabled` I run the following command `python -m pip install --upgrade --force-reinstall --no-cache-dir --no-deps torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu117`, please suggest better version, this one worked with my 3060 12GB running Windows 11

All the best!!!

**Comment by runew0lf** [comment]
Point 1 has been updated, for point 2 however, there is no need to update or download torch with cuda enabled ,its comes pre-installed in the release package
