### ISSUE TITLE
Where can we see the logs file?

### ISSUE THREAD

**Issue by ItsNoted** [runew0lf/RuinedFooocus#113]
Hey there! OG Fooocus user here trying out your fork! I love the changes but I want to see the log file if possible? Is there an HTML log file or some sort of log file so I can see exactly what wildcard words are chosen and added to my prompts? Sorry if I overlooked it!

**Comment by runew0lf** [comment]
there isnt mate, but all png info gets written to the actually images themself as metadata

**Comment by ItsNoted** [comment]
I see what I want in the info tab. All is well!
