### ISSUE TITLE
request: more then 5 loras

### ISSUE THREAD

**Issue by drago87** [runew0lf/RuinedFooocus#118]
as the title says allow us to select more then 5 loras.
if this is not already possible by using `<lora:filename:1>`
also a question about `<lora:filename:1>` if you have them in subfolders do you need to add it? as if i have a pose folder do i `<lora:filename:1>` or `<lora:pose/filename:1>`

**Comment by yownas** [comment]
The new way selecting LoRAs work fixed this. You can now have as many as you like. :) 

(This example is what it can look like if you select too many.)

![Screenshot from 2024-06-07 12-59-43](https://github.com/runew0lf/RuinedFooocus/assets/13150150/d4b4cfd4-5903-4dda-b186-42c1b6412b70)
