### ISSUE TITLE
PLZ Help .... I have a limited quota of internet 

### ISSUE THREAD

**Issue by nadora35** [runew0lf/RuinedFooocus#120]
I have a limited quota of internet
and I have a lot of model in my hdd
how i start without downloading sd_xl_base_1

**Comment by runew0lf** [comment]
create a blank text file and name it sdxl_base

**Comment by nadora35** [comment]
dosnt work

**Comment by nadora35** [comment]
???

**Comment by runew0lf** [comment]
excellent
