### ISSUE TITLE
NVIDIA driver runtime error AMD

### ISSUE THREAD

**Issue by kaarst90** [runew0lf/RuinedFooocus#121]
Hey I’m a fooocus user on amd everything is fine. Now I want to try your fork but I can’t fix the „runtime error“ cause of missing nvidia driver. For fooocus itself the problem was fixed by its own programming. Fe. Stable diffusion it only needs some commandline args that also works but here on ruinedfooocus I dont know how to skip the NVIDIA driver test. Any advice ?

**Comment by runew0lf** [comment]
sorry we only support nvisia
