### ISSUE TITLE
Author, can you set it up so that the model file is not automatically downloaded?

### ISSUE THREAD

**Issue by tanglup** [runew0lf/RuinedFooocus#133]
Several download model commands in lauch are prohibited. It will not download automatically after startup, but an error occurs. it may need to set up the module, but I don't know how. My ability can only change this.

**Comment by runew0lf** [comment]
nope

**Comment by tanglup** [comment]
> 没有

I set it up successfully and changed the default model,
Also, I want to set the interface to Chinese. Can I create a new language in the folder and then match the corresponding English and Chinese myself?
