### ISSUE TITLE
Settings (settings.json) Issues

### ISSUE THREAD

**Issue by almfisch** [runew0lf/RuinedFooocus#142]
Since the Model/Lora Tab-Update the Lora-Part in the settings.json is no more working.

Some other suggestions/questions:

- Is there an option to turn off the model/lora thumbnails? I have a lot of models and loras, some of them do not have thumbnails, so it is difficult to choose the right model, because the name is cut off
- How can I add the Flufferizer to the style-setting in the settings.json, I tried "Style: sai-cinematic, Flufferizer" but it does not work
- It would be nice to have the option to save default OneButtonPrompt-Settings in the settings.json

Many regards and thank you very much

**Comment by yownas** [comment]
1. Sorry, no. There is no way to turn off the lora thumbnails. _But_ you can go into the folder called `cache\\oras\` and change the images there for the loras that it didn't find a thumbnail for. Not what you asked for, but I hope that helps.
2. If you have more than one style you want to add you need to add them as a list, like this: `  "style": ["Style: sai-cinematic", "Flufferizer", "Style: misc-horror"],` 
3.  That is a bit trickier, but I'll see if we can fix something for that.
