### ISSUE TITLE
Do you plan support for small and big model?

### ISSUE THREAD

**Issue by ptits** [runew0lf/RuinedFooocus#144]
sd3_medium.safetensors

[15.8 GB]sd3_medium_incl_clips_t5xxlfp16.safetensors

**Comment by runew0lf** [comment]
personally no, they dont offer any bonus over the model included with the clips, apart from extra stuff to download, and the t5 doesnt product any better prompt adhesion right now. Maybe the big model we'll be adding!

**Comment by runew0lf** [comment]
i just checked the big model is supported in our latest dev version, which should be pushed to main soon!

**Comment by ptits** [comment]
So, great! Thanks for quickest response!
I got so funny results with Ruined Focus, will share it now
