### ISSUE TITLE
Parameters in prompt

### ISSUE THREAD

**Issue by ptits** [runew0lf/RuinedFooocus#146]
I know it is possible to put style into prompt with<>.
Is it possible to put Steps or other parameters into prompt?

**Comment by yownas** [comment]
Yes. You can use json as a prompt. Like this (as the prompt)):
`{"prompt": "cat", "steps": 15, "cfg": 4.5}`

You can even have multiple json-prompts after each other by splitting them up with  `---`:
```
{"prompt": "cat", "seed": 123, "steps": 5}---
{"prompt": "cat", "seed": 123, "steps": 10}---
{"prompt": "cat", "seed": 123, "steps": 15}---
{"prompt": "cat", "seed": 123, "steps": 20}
```

**Comment by ptits** [comment]
Wow, I like it more and more.

Can I use style with json? Like this:

{"prompt": "cat <style:sai-anime>", "seed": 123, "steps": 10}---

**Comment by yownas** [comment]
Yes. That should work.
