### ISSUE TITLE
Naming output files

### ISSUE THREAD

**Issue by ptits** [runew0lf/RuinedFooocus#147]
I am not sure if it is on radar, but having PNG names include style, seed or steps will be nice.
Anyway one can add it in utils.py if no plans for that

**Comment by yownas** [comment]
No. Not really anything we've planned to do.

All generation data are saved in the images. In you clear the prompt and then drop a generated image in the main image window, you'll see all the settings. (you can drop any image there, if it isn't generated by RuinedFooocus it will try to generate a prompt from what is in the image.)
