### ISSUE TITLE
ERROR: Could not install packages due to an OSError: Consider using the `--user` option or check the permissions.

### ISSUE THREAD

**Issue by Salami50** [runew0lf/RuinedFooocus#151]
Hello, I get the message when I want to install fooocus?

**Comment by yownas** [comment]
Fooocus or RuinedFooocus? Windows? Linux?
My best guess without knowing more would be that you ran out of disk space...maybe?

**Comment by Salami50** [comment]
its worked with stability matrix but i like more the official fooocus interface.

**Comment by yownas** [comment]
Ok. :)
