### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by QBANIN** [runew0lf/RuinedFooocus#173]
After running this set of commands

> git clone https://github.com/runew0lf/RuinedFooocus.git
> cd RuinedFooocus
> virtualenv venv
> source venv/bin/activate
> pip install -r requirements_versions.txt

I'm getting following error message

> root@multimedia:/opt/RuinedFooocus# python launch.py --listen
> Python 3.9.2 (default, Feb 28 2021, 17:03:44) 
> [GCC 10.2.1 20210110]
> RuinedFooocus version: 1.56.0
> Check pip
> Requirement already satisfied: pip in ./venv/lib/python3.9/site-packages (24.2)
> Comfy Backend update check complete.
> Stable Fast 3D update check complete.
> ComfyUI-GGUF update check complete.
> Traceback (most recent call last):
>   File "/opt/RuinedFooocus/launch.py", line 233, in <module>
>     from webui import *
>   File "/opt/RuinedFooocus/webui.py", line 17, in <module>
>     import modules.async_worker as worker
>   File "/opt/RuinedFooocus/modules/async_worker.py", line 51
>     match gen_data["task_type"]:
>           ^
> SyntaxError: invalid syntax
>

**Comment by yownas** [comment]
You need python >= 3.10.
