### ISSUE TITLE
Can't it be set up to just read models/LoRas from the OG Fooocus folder ?

### ISSUE THREAD

**Issue by vecuccio** [runew0lf/RuinedFooocus#180]
I'd really like to try Ruined Fooocus, but it says I have to copy my original models over to Ruined Fooocus's folder.
IE, waste hundreds of gigs of precious SSD space by duplicating files. Will there be a fix for this in the future ?

**Comment by runew0lf** [comment]
settings.json, you can set your path in there to point to the model/lora folders
