### ISSUE TITLE
ValueError: Unknown file key: cn_img2img

### ISSUE THREAD

**Issue by gorkaherrera** [runew0lf/RuinedFooocus#186]
Hi, I have a problem with the software, when I use powerUp: code Img2Img, I get the following error. 
Could you help me solve it, thank you

 line 248, in get_file_path
    raise ValueError(f"Unknown file key: {file_key}")
ValueError: Unknown file key: cn_img2img

**Comment by yownas** [comment]
Fixed here: https://github.com/runew0lf/RuinedFooocus/commit/808279a153e50964953238256117c3389f709303
(Will be merged into main soon)
