### ISSUE TITLE
Feature Request: Run with All Styles

### ISSUE THREAD

**Issue by barepixels** [runew0lf/RuinedFooocus#20]
repost from  https://github.com/MoonRide303/Fooocus-MRE/issues/96

**Comment by barepixels** [comment]
It doesn't work right.  Here is my prompt

a naked lady <style:sai-analog film> ---
a naked lady <style:artstyle-abstract expressionism> ---
a naked lady <style:sai-cinematic> ---
a naked lady <style:artstyle-watercolor> ---
a naked lady <style:photo-tilt-shift> ---
a naked lady <style:artstyle-steampunk>

It seems to add the next style to the previous style and on and on.

I tried this way too, one continuous line

a naked lady <style:sai-analog film> ---a naked lady <style:artstyle-abstract expressionism> ---a naked lady <style:sai-cinematic> ---a naked lady <style:artstyle-watercolor> ---a naked lady <style:photo-tilt-shift> ---a naked lady <style:artstyle-steampunk>

**Comment by runew0lf** [comment]
Thanks man will have a look into it!!!

**Comment by barepixels** [comment]
am not a coder but does the last line helps?

#for key in style_keys:
#style = key
#pipeline.clean_prompt_cond_caches()

**Comment by runew0lf** [comment]
Fixed buddy

**Comment by barepixels** [comment]
Tested.  Works great.  Thank you so much

Here is metadata for steampunk

{"Prompt": "\na naked lady , steampunk style \na naked lady , antique, mechanical, brass and copper tones, gears, intricate, detailed, ", "Negative": ", deformed, glitch, noisy, low contrast, anime, photorealistic, , ", "steps": 60, "switch": 40, "cfg": 8, "width": 1024, "height": 1024, "seed": 390199561, "sampler_name": "dpmpp_2m_sde_gpu", "scheduler": "karras", "base_model_name": "sd_xl_base_1.0_0.9vae.safetensors", "refiner_model_name": "sd_xl_refiner_1.0_0.9vae.safetensors", "loras": "Loras:<sd_xl_offset_example-lora_1.0.safetensors:0.5>,<None:0.5>,<None:0.5>,<None:0.5>,<None:0.5>", "start_step": 0, "denoise": null, "software": "RuinedFooocus"}

**Comment by runew0lf** [comment]
Excellent, good work mate!
