### ISSUE TITLE
Can you explain random_prompt/build_dynamic_prompt.py?

### ISSUE THREAD

**Issue by TimothyAlexisVass** [runew0lf/RuinedFooocus#21]
🤔 How does it work? 😅
Is this not limited by the CLIP 77 token limit?

**Comment by runew0lf** [comment]
it randomly builds up a prompt just like onebuttonprompt extension for stablediffusion. tbh i have no idea if its limited by the clip 77 token limit, however it uses comfy as a backend so i'm guessing it will be fine :D

**Comment by TimothyAlexisVass** [comment]
Oh, I get it, thanks! :)
