### ISSUE TITLE
run-RuinedFooocus-no-update.bat

### ISSUE THREAD

**Issue by barepixels** [runew0lf/RuinedFooocus#31]
For Fooocus-MRE the codes in **run-mre-no-update.bat** look like this:

```
@echo off
cd Fooocus-MRE
..\Fooocus-MRE-env\python.exe -s launch.py
pause
```

How to do the same for **RuinedFooocus**?

**Comment by runew0lf** [comment]
we dont have it, its always recommended to keep up with the latest upto date version

**Comment by barepixels** [comment]
I figured it out.  Closing this issue
