### ISSUE TITLE
comfyui_controlnet_aux

### ISSUE THREAD

**Issue by barepixels** [runew0lf/RuinedFooocus#33]
This is pretty cool.  Can do a lot
**[Line Extractors](https://github.com/Fannovel16/comfyui_controlnet_aux#line-extractors)**
Binary Lines
Canny Edge
HED Lines
Normal Lineart
Anime Lineart
Manga Lineart
M-LSD Lines
PiDiNet Lines
Scribble Lines
Scribble XDoG Lines
**[Normal and Depth Map](https://github.com/Fannovel16/comfyui_controlnet_aux#normal-and-depth-map)**
LeReS - Depth Map
MiDaS - Normal Map
MiDaS - Depth Map
BAE - Normal Map
Zoe - Depth Map
**[Faces and Poses](https://github.com/Fannovel16/comfyui_controlnet_aux#faces-and-poses)**
DWPose Pose Recognition  https://youtu.be/30b2k1p2CiE?si=9a5DWRx1_nUB95OP
OpenPose Pose Recognition
MediaPipe Face Mesh
**[Semantic Segmentation](https://github.com/Fannovel16/comfyui_controlnet_aux#semantic-segmentation)**
OneFormer ADE20K Segmentor
UniFormer Segmentor
OneFormer COCO Segmentor
**[T2IAdapter-only](https://github.com/Fannovel16/comfyui_controlnet_aux#t2iadapter-only)**
Color Pallete
Content Shuffle

I got it working in ComfyUI using this link  https://github.com/Fannovel16/comfyui_controlnet_aux

![DWpose](https://github.com/runew0lf/RuinedFooocus/assets/92839033/4ccbcdb8-1a7e-453b-b3d9-d2e646e2b18c)

Am hoping you will investigate and get it working in Fooocus (my preferred UI)

**Comment by runew0lf** [comment]
Sorry not for us, it would add too much complication to a simplified interface

**Comment by barepixels** [comment]
How about just OpenPose or DWPose
