### ISSUE TITLE
about the one button prompt

### ISSUE THREAD

**Issue by tiwentichat** [runew0lf/RuinedFooocus#44]
Hi Runew0lf,

The RuinedFooocus is Great!
Especially the one button prompt feature, I like it very much

You've done a wonderful work, would you like to merge  it to the current version of Fooocus by lllyasviel?
That would be a big optimazation to the Fooocus : )

**Comment by runew0lf** [comment]
Its a good idea, but there are a lot of changes that i wouldnt like to implement tbh, a lot of the codebase has changed dramatically over the last few months
