### ISSUE TITLE
Unable to change paths to Checkpoints without error

### ISSUE THREAD

**Issue by chalkncheese** [runew0lf/RuinedFooocus#46]
Hi, thanks for this fantastic web-ui. I have tried changing the location paths to my checkpoints which I have located elsewhere on my drives (used for A1111 and ComfyUI) using the Settings/path.json file so I do not have duplicate copies of the large models, but RuinedFooocus will not load. (I have changed the Windows default " \ "  to " / " on all paths.) Am I missing something ?

**Comment by serdarpolat** [comment]
I think you should play with these files:
RuinedFooocus/launch.py
![Ekran görüntüsü 2023-10-24 025754](https://github.com/runew0lf/RuinedFooocus/assets/7966503/6f1b56eb-2ebd-4fbb-ad30-ac376f10e13f)

RuinedFooocus/settings/paths.json
![Ekran görüntüsü 2023-10-24 025734](https://github.com/runew0lf/RuinedFooocus/assets/7966503/522579a9-5b54-4940-a200-b87cb27c2fa9)

RuinedFooocus/modules/path.py
![Ekran görüntüsü 2023-10-24 025720](https://github.com/runew0lf/RuinedFooocus/assets/7966503/3861499d-eb5b-4aad-9030-d747ed9bed62)

**Comment by runew0lf** [comment]
please do not start messing with the source code :D `paths.json` is perfectly enough to change: json is weird with \, so the paths i would put them using a `\\` instead of a `\` ie `D:\\auto11\\models\\stablediffusion\\` etc etc

**Comment by chalkncheese** [comment]
Thanks, I will try using " \\ " instead.

**Comment by chalkncheese** [comment]
Working fine now using " \\ " in location paths.

**Comment by runew0lf** [comment]
Fantastic, good to hear!
