### ISSUE TITLE
List Index Out of Range

### ISSUE THREAD

**Issue by bulutharbeli** [runew0lf/RuinedFooocus#47]
![image](https://github.com/runew0lf/RuinedFooocus/assets/30212464/bed5d438-789c-49d6-97e2-8be2f5c1b0d6)

**Comment by runew0lf** [comment]
Did you do a git pull, or did you follow the readme and installed it from the releases section?

**Comment by bulutharbeli** [comment]
When try to git pull, it gives an error. 
![image](https://github.com/runew0lf/RuinedFooocus/assets/30212464/4e30a242-3276-4a81-bb24-b5e4b45316c0)
 It is asking to run setup.py but no such file is in ruinedfoocus folder. 
![image](https://github.com/runew0lf/RuinedFooocus/assets/30212464/769665eb-f5df-4329-a51b-4329b0682e3a)

**Comment by runew0lf** [comment]
yeah you dont need to do any of that, i would delete the folder and follow the installation instructions in the readme

**Comment by bulutharbeli** [comment]
But I followed the instructions in the readme file. I deleted the folder twice and installed a fresh setup.

**Comment by runew0lf** [comment]
join the discord mate, its a lot easier to offer technical help than github issues

**Comment by bulutharbeli** [comment]
> join the discord mate, its a lot easier to offer technical help than github issues

yes i did thnx
