### ISSUE TITLE
A very practical function [inpaint upload] Mask Redraw, I hope it can be added! 

### ISSUE THREAD

**Issue by hzeasy** [runew0lf/RuinedFooocus#50]
Hello, I learned about your project from lllyasviel, downloaded it and tried it. It is indeed very good and implements some functions that FOOOCUS did not have before. As a graphic designer, I am looking for a better tool. If it can realize the mask redraw function of webui, it will help my design work.
![278429259-eb83ecde-bf46-4c24-ad46-69dcca445eb7](https://github.com/runew0lf/RuinedFooocus/assets/136664755/b8dace68-6d49-4496-b65b-a6e00d402c95)

And I'm sure most designers would love this feature I came up with, thank you for your work!

**Comment by barepixels** [comment]
Mabybe this codes will work

https://github.com/lllyasviel/Fooocus/compare/main...xingren23:Fooocus:uploaed_inpaint_mask

from this pull request
https://github.com/lllyasviel/Fooocus/pull/529

**Comment by runew0lf** [comment]
They are 2 totally different programs now with a gazillion changes between them

**Comment by barepixels** [comment]
I have been wanting to ask you this.  Will you create a second Fork for newer Fooocus since it's now a different beast.

Maybe starting from scratch would be easier.

**Comment by runew0lf** [comment]
Nope i wont be creating a seperate fork for it, its branched and pretty much how it is, we have different visions of how things should go, its also why MRE didnt have the time to keep up with the changes between versions

**Comment by barepixels** [comment]
Can you help me with this?  https://github.com/barepixels/Fooocus-Meta/issues/1

**Comment by runew0lf** [comment]
inpainting has been added
