### ISSUE TITLE
errors when generating a second time

### ISSUE THREAD

**Issue by pralium444** [runew0lf/RuinedFooocus#51]
Hello,  i launch it without errors, i generate a few images, then i change the prompt and try to generate again but each time i have this error : 

`To create a public link, set `share=True` in `launch()`.
Loading base model: sd_xl_base_1.0_0.9vae.safetensors
Base model loaded: sd_xl_base_1.0_0.9vae.safetensors
App started successful. Use the app with http://127.0.0.1:7860/ or 127.0.0.1:7860
Loading base model: thinkdiffusionxl_v10.safetensors
Base model loaded: thinkdiffusionxl_v10.safetensors
Loading LoRAs: sd_xl_offset_example-lora_1.0.safetensors
LoRAs loaded: [('sd_xl_offset_example-lora_1.0.safetensors', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5), ('None', 0.5)]
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [02:07<00:00,  4.24s/it]
Time taken: 133.85 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [02:12<00:00,  4.41s/it]
Time taken: 138.86 seconds
100%|██████████████████████████████████████████████████████████████████████████████████| 30/30 [02:15<00:00,  4.50s/it]
Time taken: 141.66 seconds
Exception in thread Thread-2 (worker):
Traceback (most recent call last):
  File "threading.py", line 1016, in _bootstrap_inner
  File "threading.py", line 953, in run
  File "C:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\modules\async_worker.py", line 263, in worker
    handler(task)
  File "C:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\modules\async_worker.py", line 51, in handler
    process(gen_data)
  File "C:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\modules\async_worker.py", line 187, in process
    p_txt += lora_keywords
TypeError: can only concatenate str (not "NoneType") to str`

if i close ruined Fooocus and relaunch, i can generate again, but not a second time, i have to close it again

Install on Win11, python 3.10.9, downloaded the portable version, nothing changed or moved

Thanks for the help

**Comment by runew0lf** [comment]
Sorry man, fixed the issue!!!
