### ISSUE TITLE
error, with fresh install

### ISSUE THREAD

**Issue by pralium444** [runew0lf/RuinedFooocus#61]
i redownloaded everything and this error appears : 
`
C:\AI\RuinedFooocus_win641-0-0>.\python_embeded\python.exe -s RuinedFooocus\entry_with_update.py
Fast-forward merge
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
RuinedFooocus version: 1.16.0
Inference Engine exists.
Inference Engine checkout finished.
Installing requirements
Traceback (most recent call last):
  File "C:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "C:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\launch.py", line 170, in <module>
    prepare_environment()
  File "C:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\launch.py", line 83, in prepare_environment
    run_pip(f'install -r "{requirements_file}"', "requirements")
  File "C:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\modules\launch_util.py", line 96, in run_pip
    return run(
  File "C:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\modules\launch_util.py", line 89, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install requirements.
Command: "C:\AI\RuinedFooocus_win641-0-0\python_embeded\python.exe" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: Requirement already satisfied: torchsde==0.2.5 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 1)) (0.2.5)
Requirement already satisfied: einops==0.4.1 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 2)) (0.4.1)
Requirement already satisfied: transformers==4.30.2 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 3)) (4.30.2)
Requirement already satisfied: safetensors==0.3.1 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 4)) (0.3.1)
Requirement already satisfied: accelerate==0.21.0 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 5)) (0.21.0)
Requirement already satisfied: pyyaml==6.0 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 6)) (6.0)
Requirement already satisfied: Pillow==9.2.0 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 7)) (9.2.0)
Requirement already satisfied: scipy==1.9.3 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 8)) (1.9.3)
Requirement already satisfied: tqdm==4.64.1 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 9)) (4.64.1)
Requirement already satisfied: psutil==5.9.5 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 10)) (5.9.5)
Requirement already satisfied: numpy==1.23.5 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 11)) (1.23.5)
Requirement already satisfied: pytorch_lightning==1.9.4 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 12)) (1.9.4)
Requirement already satisfied: omegaconf==2.2.3 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 13)) (2.2.3)
Collecting gradio==3.47.1 (from -r requirements_versions.txt (line 14))
  Using cached gradio-3.47.1-py3-none-any.whl (20.3 MB)
Requirement already satisfied: pygit2==1.12.2 in c:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 15)) (1.12.2)
Collecting aiohttp==3.8.5 (from -r requirements_versions.txt (line 16))
  Using cached aiohttp-3.8.5-cp310-cp310-win_amd64.whl (323 kB)
Collecting playsound2==1.3.0 (from -r requirements_versions.txt (line 17))
  Using cached playsound2-1.3.0-py3-none-any.whl
Collecting diffusers==0.21.4 (from -r requirements_versions.txt (line 18))
  Using cached diffusers-0.21.4-py3-none-any.whl (1.5 MB)
Collecting insightface==0.7.3 (from -r requirements_versions.txt (line 19))
  Using cached insightface-0.7.3.tar.gz (439 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

stderr:   error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [15 lines of output]
  Traceback (most recent call last):
    File "C:\Users\AI\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\AI\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\AI\AppData\Roaming\Python\Python310\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\AI\RuinedFooocus_win641-0-0\python_embeded\lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\AI\RuinedFooocus_win641-0-0\python_embeded\lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "C:\AI\RuinedFooocus_win641-0-0\python_embeded\lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 11, in <module>
  ModuleNotFoundError: No module named 'Cython'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.1.2 -> 23.3.1
[notice] To update, run: C:\AI\RuinedFooocus_win641-0-0\python_embeded\python.exe -m pip install --upgrade pip

C:\AI\RuinedFooocus_win641-0-0>pause
Appuyez sur une touche pour continuer...`

**Comment by yownas** [comment]
I've pushed an update that does that. Re-running `run.bat` should be enough now. 
(Sorry for breaking things.)

**Comment by pralium444** [comment]
thanks to@gmthedoc ! it works!
