### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by Eleksar387** [runew0lf/RuinedFooocus#70]
I had RuinedFoocus already running successfully. However after the update today I get this error

`Collecting future (from basicsr>=1.4.2->gfpgan==1.3.8->-r requirements_versions.txt (line 22))
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\arebh\AppData\Local\Temp\pip-install-2znkkcnj\future_4069cae2368c409184cc58be41ec6a58\setup.py", line 86, in <module>
      import src.future
  ModuleNotFoundError: No module named 'src'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.`

**Comment by runew0lf** [comment]
Just pushed a quick commit to see if we can fix this for you, there seems to be an issue with the correct version of basicsr needing to be installed priot to gfpgan 1.3.8

**Comment by Eleksar387** [comment]
Thx a lot. Unfortunately it didn't help

here is the error log:

`F:\AI\RuinedFooocus_win641-0-0>run.bat

F:\AI\RuinedFooocus_win641-0-0>.\python_embeded\python.exe -s RuinedFooocus\entry_with_update.py
Fast-forward merge
Update succeeded.
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
RuinedFooocus version: 1.17.0
Inference Engine exists.
Inference Engine checkout finished.
Installing requirements
Traceback (most recent call last):
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\entry_with_update.py", line 46, in <module>
    from launch import *
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\launch.py", line 203, in <module>
    prepare_environment()
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\launch.py", line 103, in prepare_environment
    run_pip(f'install -r "{requirements_file}"', "requirements")
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\modules\launch_util.py", line 96, in run_pip
    return run(
  File "F:\AI\RuinedFooocus_win641-0-0\RuinedFooocus\modules\launch_util.py", line 89, in run
    raise RuntimeError("\n".join(error_bits))
RuntimeError: Couldn't install requirements.
Command: "F:\AI\RuinedFooocus_win641-0-0\python_embeded\python.exe" -m pip install -r "requirements_versions.txt" --prefer-binary
Error code: 1
stdout: Requirement already satisfied: torchsde==0.2.5 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 1)) (0.2.5)
Requirement already satisfied: einops==0.4.1 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 2)) (0.4.1)
Requirement already satisfied: transformers==4.30.2 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 3)) (4.30.2)
Requirement already satisfied: safetensors==0.3.1 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 4)) (0.3.1)
Requirement already satisfied: accelerate==0.21.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 5)) (0.21.0)
Requirement already satisfied: pyyaml==6.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 6)) (6.0)
Requirement already satisfied: Pillow==9.2.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 7)) (9.2.0)
Requirement already satisfied: scipy==1.9.3 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 8)) (1.9.3)
Requirement already satisfied: tqdm==4.64.1 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 9)) (4.64.1)
Requirement already satisfied: psutil==5.9.5 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 10)) (5.9.5)
Requirement already satisfied: numpy==1.23.5 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 11)) (1.23.5)
Requirement already satisfied: pytorch_lightning==1.9.4 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 12)) (1.9.4)
Requirement already satisfied: omegaconf==2.2.3 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 13)) (2.2.3)
Requirement already satisfied: gradio==3.47.1 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 14)) (3.47.1)
Requirement already satisfied: pygit2==1.12.2 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 15)) (1.12.2)
Requirement already satisfied: aiohttp==3.8.5 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 16)) (3.8.5)
Requirement already satisfied: playsound2==1.3.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 17)) (1.3.0)
Collecting diffusers==0.23.0 (from -r requirements_versions.txt (line 18))
  Using cached diffusers-0.23.0-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: insightface==0.7.3 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 19)) (0.7.3)
Requirement already satisfied: onnxruntime-gpu==1.16.1 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 20)) (1.16.1)
Requirement already satisfied: imageio==2.31.6 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from -r requirements_versions.txt (line 21)) (2.31.6)
Collecting basicsr==1.4.2 (from -r requirements_versions.txt (line 22))
  Using cached basicsr-1.4.2-py3-none-any.whl
Collecting gfpgan==1.3.8 (from -r requirements_versions.txt (line 23))
  Using cached gfpgan-1.3.8-py3-none-any.whl (52 kB)
Requirement already satisfied: boltons>=20.2.1 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from torchsde==0.2.5->-r requirements_versions.txt (line 1)) (23.0.0)
Requirement already satisfied: torch>=1.6.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from torchsde==0.2.5->-r requirements_versions.txt (line 1)) (2.0.1+cu118)
Requirement already satisfied: trampoline>=0.1.2 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from torchsde==0.2.5->-r requirements_versions.txt (line 1)) (0.1.2)
Requirement already satisfied: filelock in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (3.12.2)
Requirement already satisfied: huggingface-hub<1.0,>=0.14.1 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (0.15.1)
Requirement already satisfied: packaging>=20.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (23.1)
Requirement already satisfied: regex!=2019.12.17 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (2023.6.3)
Requirement already satisfied: requests in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (2.31.0)
Requirement already satisfied: tokenizers!=0.11.3,<0.14,>=0.11.1 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from transformers==4.30.2->-r requirements_versions.txt (line 3)) (0.13.3)
Requirement already satisfied: colorama in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from tqdm==4.64.1->-r requirements_versions.txt (line 9)) (0.4.6)
Requirement already satisfied: fsspec>2021.06.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from fsspec[http]>2021.06.0->pytorch_lightning==1.9.4->-r requirements_versions.txt (line 12)) (2023.6.0)
Requirement already satisfied: torchmetrics>=0.7.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 12)) (1.0.3)
Requirement already satisfied: typing-extensions>=4.0.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 12)) (4.7.1)
Requirement already satisfied: lightning-utilities>=0.6.0.post0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from pytorch_lightning==1.9.4->-r requirements_versions.txt (line 12)) (0.9.0)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from omegaconf==2.2.3->-r requirements_versions.txt (line 13)) (4.9.3)
Requirement already satisfied: aiofiles<24.0,>=22.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (23.2.1)
Requirement already satisfied: altair<6.0,>=4.2.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (5.0.1)
Requirement already satisfied: fastapi in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (0.101.0)
Requirement already satisfied: ffmpy in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (0.3.1)
Requirement already satisfied: gradio-client==0.6.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (0.6.0)
Requirement already satisfied: httpx in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (0.24.1)
Requirement already satisfied: importlib-resources<7.0,>=1.3 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (6.1.0)
Requirement already satisfied: jinja2<4.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (3.1.2)
Requirement already satisfied: markupsafe~=2.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (2.1.3)
Requirement already satisfied: matplotlib~=3.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (3.7.2)
Requirement already satisfied: orjson~=3.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (3.9.4)
Requirement already satisfied: pandas<3.0,>=1.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (2.0.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,!=2.0.0,!=2.0.1,<3.0.0,>=1.7.4 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (2.1.1)
Requirement already satisfied: pydub in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (0.25.1)
Requirement already satisfied: python-multipart in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (0.0.6)
Requirement already satisfied: semantic-version~=2.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (2.10.0)
Requirement already satisfied: uvicorn>=0.14.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (0.23.2)
Requirement already satisfied: websockets<12.0,>=10.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from gradio==3.47.1->-r requirements_versions.txt (line 14)) (11.0.3)
Requirement already satisfied: cffi>=1.9.1 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from pygit2==1.12.2->-r requirements_versions.txt (line 15)) (1.15.1)
Requirement already satisfied: attrs>=17.3.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from aiohttp==3.8.5->-r requirements_versions.txt (line 16)) (23.1.0)
Requirement already satisfied: charset-normalizer<4.0,>=2.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from aiohttp==3.8.5->-r requirements_versions.txt (line 16)) (3.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from aiohttp==3.8.5->-r requirements_versions.txt (line 16)) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from aiohttp==3.8.5->-r requirements_versions.txt (line 16)) (4.0.2)
Requirement already satisfied: yarl<2.0,>=1.0 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from aiohttp==3.8.5->-r requirements_versions.txt (line 16)) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from aiohttp==3.8.5->-r requirements_versions.txt (line 16)) (1.3.3)
Requirement already satisfied: aiosignal>=1.1.2 in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from aiohttp==3.8.5->-r requirements_versions.txt (line 16)) (1.3.1)
Requirement already satisfied: importlib-metadata in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from diffusers==0.23.0->-r requirements_versions.txt (line 18)) (6.8.0)
Requirement already satisfied: onnx in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from insightface==0.7.3->-r requirements_versions.txt (line 19)) (1.15.0)
Requirement already satisfied: scikit-learn in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from insightface==0.7.3->-r requirements_versions.txt (line 19)) (1.3.2)
Requirement already satisfied: scikit-image in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from insightface==0.7.3->-r requirements_versions.txt (line 19)) (0.22.0)
Requirement already satisfied: easydict in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from insightface==0.7.3->-r requirements_versions.txt (line 19)) (1.11)
Requirement already satisfied: cython in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from insightface==0.7.3->-r requirements_versions.txt (line 19)) (3.0.5)
Requirement already satisfied: albumentations in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from insightface==0.7.3->-r requirements_versions.txt (line 19)) (1.3.1)
Requirement already satisfied: prettytable in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from insightface==0.7.3->-r requirements_versions.txt (line 19)) (3.9.0)
Requirement already satisfied: coloredlogs in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from onnxruntime-gpu==1.16.1->-r requirements_versions.txt (line 20)) (15.0.1)
Requirement already satisfied: flatbuffers in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from onnxruntime-gpu==1.16.1->-r requirements_versions.txt (line 20)) (23.5.26)
Requirement already satisfied: protobuf in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from onnxruntime-gpu==1.16.1->-r requirements_versions.txt (line 20)) (4.25.0)
Requirement already satisfied: sympy in f:\ai\ruinedfooocus_win641-0-0\python_embeded\lib\site-packages (from onnxruntime-gpu==1.16.1->-r requirements_versions.txt (line 20)) (1.12)
Collecting addict (from basicsr==1.4.2->-r requirements_versions.txt (line 22))
  Using cached addict-2.4.0-py3-none-any.whl (3.8 kB)
Collecting future (from basicsr==1.4.2->-r requirements_versions.txt (line 22))
  Using cached future-0.18.3.tar.gz (840 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'

stderr:   error: subprocess-exited-with-error

  python setup.py egg_info did not run successfully.
  exit code: 1

  [6 lines of output]
  Traceback (most recent call last):
    File "<string>", line 2, in <module>
    File "<pip-setuptools-caller>", line 34, in <module>
    File "C:\Users\arebh\AppData\Local\Temp\pip-install-bhttu4y_\future_fe316de62e9040e9b984f847d63d1605\setup.py", line 86, in <module>
      import src.future
  ModuleNotFoundError: No module named 'src'
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

Encountered error while generating package metadata.

See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by runew0lf** [comment]
One thing you could give me a try if thats ok mate
You should have a folder called python_embeded n the same folder where you have run.bat. Rename that folder and copy the python_embeded folder from the archive. It looks like the old one is broken...somehow.

**Comment by Eleksar387** [comment]
Sure. But what archive do you mean?

**Comment by runew0lf** [comment]
Excellent thats really good to know!!!!!
