### ISSUE TITLE
Allow weight less than -2 and greater than 2.

### ISSUE THREAD

**Issue by ujl123** [runew0lf/RuinedFooocus#98]
There are some "slider" style loras that use weights from -15 to 15 to trigger specific styles. There are several more but nsfw so I won't link to them directly but searching for "slider" will return them.

https://civitai.com/models/205816/test-slider-lora-sdxl-longshort-hair

**Comment by runew0lf** [comment]
I did a quick little test however the slider adjustment then turns useless with such a range, especially with steps of 0.05, i do however recommend if you are wanting such large numbers for a slider you can use <loraname:15> or <lorname:-15> that should give you some more control with the large ranges

**Comment by ujl123** [comment]
Thanks for the alternative! I did change the html so that it accepts a max value of 15 and steps of 0.5 in order to accommodate the large value so you are right that you can't just increase the value alone. I had forgotten that you can use loras by name. I should really re-read the wiki.

**Comment by ujl123** [comment]
@runew0lf  Would you be able to clarify the correct nomenclature for using loras inline?  lora:filename:15 and filename:15 doesn't seem to work on my end. The info tab doesn't say the lora is applied (understandable as it only reports on the dropdown loras) but the image itself also does not have the lora applied, even at 15 strength

**Comment by runew0lf** [comment]
its `<lora:filename:15>`
